---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: opscode-ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
suites:
  - name: default
    run_list:
      - recipe[consul_do::default]
      - recipe[minitest-handler]
    attributes:

settings:
  parallel: true
